version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app56.dockerfile
    working_dir: /var/www
    volumes:
      - ./www/:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: daocloud.io/mysql:5.7.4
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=fastadmin"
      - "MYSQL_USER=fast"
      - "MYSQL_PASSWORD=fast"
      - "MYSQL_ROOT_PASSWORD=fastsecret"
    ports:
        - "3306:3306"

  redis:
    image: daocloud.io/library/redis:4.0.10-alpine
    command: redis-server --appendonly yes

#volumes:
####  dbdata:

